## 第10章 函数

**函数是对象，是Function()的实例，函数名是指向函数的指针**

### 1. 创建函数

```js
// 函数声明，会提升
function sum (num1, num2) {
	return num1 + num2;
}

// 另一种定义函数的语法是函数表达式。函数表达式与函数声明几乎是等价的：
let sum = function(num1, num2) {
	return num1 + num2;
};

// 箭头函数
let sum = (num1, num2) => {
	return num1 + num2;
};
```

### 2. 箭头函数

箭头函数的this，在定义时找

只有一个参数，可以不写括号。

``` js
// 以下两种写法都有效
let double = (x) => { return 2 * x; };
let triple = x => { return 3 * x; };
// 没有参数需要括号
let getRandom = () => { return Math.random(); };
// 多个参数需要括号
let sum = (a, b) => { return a + b; };
// 无效的写法：
let multiply = a, b => { return a * b; };
```

不使用大括号，那么箭头后面就只能有一行代码，比如一个赋值操作，或者一个表达式。而且，省略大括号会隐式返回这行代码的值

```js
// 以下两种写法都有效，而且返回相应的值
let double = (x) => { return 2 * x; };
let triple = (x) => 3 * x;
// 可以赋值
let value = {};
let setName = (x) => x.name = "Matt";
setName(value);
console.log(value.name); // "Matt"
// 无效的写法：
let multiply = (a, b) => return a * b;
```

**适用场景**：箭头函数虽然语法简洁，但也有很多场合不适用。箭头函数不能使用 arguments 、 super 和new.target ，也不能用作构造函数。此外，箭头函数也没有 prototype 属性。**适合嵌入使用**。

返回一个对象，可以用如下写法，用大括号包起来

```js
let test = () => ({
    
})
```



### 3. 函数名

函数名就是指向函数的指针，并且一个函数可以有多个函数名。

```js
function sum(num1, num2) {
	return num1 + num2;
}

console.log(sum(10, 10)); // 20
// anotherSum也指向sum指向的函数
let anotherSum = sum;
console.log(anotherSum(10, 10)); // 20
// sum指空之后，anotherSum不变
sum = null;
console.log(anotherSum(10, 10)); // 20
```

**name属性**

ECMAScript 6 的所有函数对象都会暴露一个只读的 name 属性，其中包含关于函数的信息。多数情
况下，这个属性中保存的就是一个函数标识符，或者说是一个字符串化的变量名。

* 正常显示函数名称

* 没有名称，显示成空字符串

* 使用 Function 构造函数创建的，则会标识成 "anonymous" 

* 如果函数是一个获取函数、设置函数，或者使用 bind() 实例化，那么标识符前面会加上一个前缀

```js
function foo() {}
let bar = function() {};
let baz = () => {};

console.log(foo.name); // foo
console.log(bar.name); // bar
console.log(baz.name); // baz
console.log((() => {}).name); //（空字符串）
console.log((new Function()).name); // anonymous
```

```js
function foo() {}
	console.log(foo.bind(null).name); // bound foo
let dog = {
    years: 1,
    get age() {
    	return this.years;
    },
    set age(newAge) {
    	this.years = newAge;
    }
}
let propertyDescriptor = Object.getOwnPropertyDescriptor(dog, 'age');
console.log(propertyDescriptor.get.name); // get age
console.log(propertyDescriptor.set.name); // set age
```

### 4. 函数参数

#### 4.1 arguments

特点：调用时传入的参数个数随意，都不会报错

原因：函数参数是一个类数组arguments

```js
// 可以通过arguments[n]来访问传入的参数
// 这两个函数的效果等同
function sayHi(name, message) {
	console.log("Hello " + name + ", " + message);
}

function sayHi() {
	console.log("Hello " + arguments[0] + ", " + arguments[1]);
}
```

```js
// 有length属性，可以得知传入参数的长度
function howManyArgs() {
	console.log(arguments.length);
}
howManyArgs("string", 45); // 2
howManyArgs(); // 0
howManyArgs(12); // 1
```

**箭头函数没有arguments对象**

**callee属性**

arguments.callee指向arguments对象所在函数，严格模式下访问会报错。

```js
function factorial(num) {
    if (num <= 1) {
    	return 1;
    } else {
    	return num * factorial(num - 1);
    }
}
```

```js
// 使用arguments.callee实现函数逻辑与函数名解耦，如果用另一个名字指向这个函数，也能成立
function factorial(num) {
	if (num <= 1) {
    	return 1;
    } else {
    	return num * arguments.callee(num - 1);
    }
}
```



#### 4.2 默认参数

```js
function makeKing(name = 'Henry') {
	return `King ${name} VIII`;
}
console.log(makeKing('Louis')); // 'King Louis VIII'
console.log(makeKing()); // 'King Henry VIII'
```

**arguments对象的值始终反映传入参数的值**

```js
function makeKing(name = 'Henry') {
    name = 'Louis';
    return `King ${arguments[0]}`;
}
console.log(makeKing()); // 'King undefined'
console.log(makeKing('Louis')); // 'King Louis'
```

#### 4.3 扩展参数

将数组中的每个元素作为函数的参数

```js
let values = [1, 2, 3, 4];
function getSum() {
    let sum = 0;
    for (let i = 0; i < arguments.length; ++i) {
    	sum += arguments[i];
    }
    return sum;
}

// 使用...语法
console.log(getSum(...values)); // 10
// 也可以再传其他值
console.log(getSum(-1, ...values)); // 9
console.log(getSum(...values, 5)); // 15
console.log(getSum(-1, ...values, 5)); // 14
console.log(getSum(...values, ...[5,6,7])); // 28
```

### 5. this

#### 1. **默认绑定**

在全局空间中独立调用一个函数，此时的this会指向全局对象。严格模式下，不会发生默认绑定，this会指向undefined。

```js
function foo() {
	console.log( this.a );
}

var a = 2;
foo(); // 2
```

#### 2. **隐式绑定**

函数被对象包含，this指向这个对象

```js
function foo() {
	console.log( this.a );
}
var obj = {
    a: 2,
    foo: foo
};
obj.foo(); // 2
```

this指向最后一个包含的对象

```js
function foo() {
	console.log( this.a );
}
var obj2 = {
    a: 42,
    foo: foo
};
var obj1 = {
    a: 2,
    obj2: obj2
};
obj1.obj2.foo(); // 42
```

```js
// 虽然 bar 是 obj.foo 的一个引用，但是实际上，它引用的是 foo 函数本身，因此应用默认绑定
function foo() {
	console.log( this.a );
}
var obj = {
	a: 2,
	foo: foo
};

var bar = obj.foo; // 函数别名！
var a = "oops, global"; // a 是全局对象的属性
bar(); // "oops, global"
```

#### 3. 显式绑定

* 使用call()，apply()方法，第一个参数是this要绑定的对象

* 一些其他的函数会指定this绑定的对象，比如foreach的第二个参数

```js
function foo() {
	console.log( this.a );
}
var obj = {
	a:2
};
foo.call( obj ); // 2
```

#### 4. new绑定

将this绑定到新创建的对象上

#### 5. 箭头函数

this由包含箭头函数的块决定

```js
const obj = {
    aaa() {
      // setTimeout会调用call()，把window作为参数传入，
      // 相当于window来调用这个函数，所以this指代window
      setTimeout(function () {
        console.log(this); // window
      })
	 
      // 箭头函数向外找，忽略setTimeout()，所以this由aaa()决定，即obj
      setTimeout(() => {
        console.log(this); // obj对象
      })
    }
  }

  obj.aaa()
```

```js
  const obj = {
    aaa() {
      setTimeout(function () { // 1
        setTimeout(function () {
          console.log(this); // window
        })
        // 向外找，由1处的function() 决定，为window
        setTimeout(() => {
          console.log(this); // window
        })
      })
		
      setTimeout(() => { // 2
        setTimeout(function () {
          console.log(this); // window
        })
		// 向外找，找到2，依旧是箭头函数，继续向外找，找到aaa()，this指向obj
        setTimeout(() => {
          console.log(this); // obj
        })
      })
    }
  }

  obj.aaa()
```



**优先级**

new > 显式 > 隐式 > 默认

### 6. new.target

ECMAScript 6 新增了检测函数是否使用 new 关键字调用的 new.target 属性。如果函数是正常调用的，则 new.target 的值是 undefined ；如果是使用 new 关键字调用的，则 new.target 将引用被调用的构造函数。

```js
function King() {
    if (!new.target) {
    	throw 'King must be instantiated using "new"'
	}
	console.log('King instantiated using "new"');
}
new King(); // King instantiated using "new"
King(); // Error: King must be instantiated using "new"
```

### 7. 函数属性和方法

ES中的函数是对象，因此有属性和方法

#### 7.1 属性

每个函数都有两个属性：length, prototype

length：函数定义的命名参数的个数

```js
function sayName(name) {
	console.log(name);
}
function sum(num1, num2) {
	return num1 + num2;
}
function sayHi() {
	console.log("hi");
}

console.log(sayName.length); // 1
console.log(sum.length); // 2
console.log(sayHi.length); // 0
```

prototype：指向原型对象，不可枚举。

#### 7.2 方法

`apply()` `call()` `bind()`

作用：显式的绑定`this`

`apply()` 方法接收两个参数：第一个参数指定this绑定的对象，第二个参数是要传入参数数组。

可以是 `Array` 的实例，但也可以是 `arguments` 对象。

`call()`方法接收多个参数：第一个参数指定this绑定的对象，后面的参数都是要传入的参数。

`bind()`会创建一个新的函数实例。后面是一系列参数

```js
// apply
function sum(num1, num2) {
	return num1 + num2;
}

// callSum1绑定的this（此处为window)来调用sum函数，并给sum函数传入callSum1的arguments对象
function callSum1(num1, num2) {
	return sum.apply(this, arguments); // 传入 arguments 对象
}

function callSum2(num1, num2) {
	return sum.apply(this, [num1, num2]); // 传入数组
}

console.log(callSum1(10, 10)); // 20
console.log(callSum2(10, 10)); // 20
```

```js
// call
function sum(num1, num2) {
	return num1 + num2;
}
// 必须把要传入的参数一个个罗列出来
function callSum(num1, num2) {
	return sum.call(this, num1, num2);
}
console.log(callSum(10, 10)); // 20
```

```js
// bind
window.color = 'red';
var o = {
	color: 'blue'
};
function sayColor() {
	console.log(this.color);
}
let objectSayColor = sayColor.bind(o);
objectSayColor(); // blue
```

对函数而言，继承的方法 toLocaleString() 和 toString() 始终返回函数的代码。返回代码的具体格式因浏览器而异。有的返回源代码，包含注释，而有的只返回代码的内部形式，会删除注释，甚至代码可能被解释器修改过。由于这些差异，因此不能在重要功能中依赖这些方法返回的值，而只应在调试中使用它们。继承的方法 valueOf() 返回函数本身。

### 8. 闭包

[详见](https://blog.csdn.net/weixin_43586120/article/details/89456183)

#### 1) 概念

**闭包函数：**声明在一个函数中的函数，叫做闭包函数。

**闭包：**内部函数总是可以访问其所在的外部函数中声明的参数和变量，即使在其外部函数被返回（寿命终结）了之后。

#### 2) 特点

```
让外部访问函数内部变量成为可能；

局部变量会常驻在内存中；

可以避免使用全局变量，防止全局变量污染；

会造成内存泄漏（有一块内存空间被长期占用，而不被释放）
```

局部变量常驻内存中，指的是被内部函数引用的变量不会被销毁，可以长期保存，也因此可以避免使用全局变量，防止全局变量污染

例子如下：

```js
var i = 0;
function outerFn(){
  function innnerFn(){
       i++;
       console.log(i);
  }
  return innnerFn;
}
var inner1 = outerFn();
var inner2 = outerFn();
inner1();
inner2();
inner1();
inner2();     //1 2 3 4
```

```
function fn(){
	var a = 3;
	return function(){
		return  ++a;                                     
	}
}
alert(fn()());  //4
alert(fn()());  //4  
```

```
function outerFn(){
var i = 0;
  function innnerFn(){
      i++;
      console.log(i);
  }
  return innnerFn;
}
var inner1 = outerFn();
var inner2 = outerFn();
inner1();
inner2();
inner1();
inner2();    //1 1 2 2
```

### 9. 尾调用优化

ECMAScript 6 规范新增了一项内存管理优化机制，让 JavaScript 引擎在满足条件时可以重用栈帧。
具体来说，这项优化非常适合“尾调用”，即外部函数的返回值是一个内部函数的返回值。比如：

```js
function outerFunction() {
 return innerFunction(); // 尾调用
}
```

在 ES6 优化之前，执行这个例子会在内存中发生如下操作。
(1) 执行到 outerFunction 函数体，第一个栈帧被推到栈上。
(2) 执行 outerFunction 函数体，到 return 语句。计算返回值必须先计算 innerFunction。
(3) 执行到 innerFunction 函数体，第二个栈帧被推到栈上。
(4) 执行 innerFunction 函数体，计算其返回值。
(5) 将返回值传回 outerFunction，然后 outerFunction 再返回值。
(6) 将栈帧弹出栈外。
在 ES6 优化之后，执行这个例子会在内存中发生如下操作。
(1) 执行到 outerFunction 函数体，第一个栈帧被推到栈上。
(2) 执行 outerFunction 函数体，到达 return 语句。为求值返回语句，必须先求值 innerFunction。
(3) 引擎发现把第一个栈帧弹出栈外也没问题，因为 innerFunction 的返回值也是 outerFunction
的返回值。
(4) 弹出 outerFunction 的栈帧。
(5) 执行到 innerFunction 函数体，栈帧被推到栈上。
(6) 执行 innerFunction 函数体，计算其返回值。
(7) 将 innerFunction 的栈帧弹出栈外。
很明显，第一种情况下每多调用一次嵌套函数，就会多增加一个栈帧。而第二种情况下无论调用多
少次嵌套函数，都只有一个栈帧。这就是 ES6 尾调用优化的关键：如果函数的逻辑允许基于尾调用将其
销毁，则引擎就会那么做。
注意 现在还没有办法测试尾调用优化是否起作用。不过，因为这是 ES6 规范所规定的，
兼容的浏览器实现都能保证在代码满足条件的情况下应用这个优化。
10.13.1 尾调用优化的条件
尾调用优化的条件就是确定外部栈帧真的没有必要存在了。涉及的条件如下：
 代码在严格模式下执行；
 外部函数的返回值是对尾调用函数的调用；
 尾调用函数返回后不需要执行额外的逻辑；
 尾调用函数不是引用外部函数作用域中自由变量的闭包。
下面展示了几个违反上述条件的函数，因此都不符号尾调用优化的要求：

```js
"use strict";
// 无优化：尾调用没有返回
function outerFunction() {
 innerFunction();
}
// 无优化：尾调用没有直接返回
function outerFunction() {
 let innerFunctionResult = innerFunction();
 return innerFunctionResult;
}
// 无优化：尾调用返回后必须转型为字符串
function outerFunction() {
 return innerFunction().toString();
}
// 无优化：尾调用是一个闭包
function outerFunction() {
 let foo = 'bar';
 function innerFunction() { return foo; }
 return innerFunction();
}
// 下面是几个符合尾调用优化条件的例子：

"use strict";
// 有优化：栈帧销毁前执行参数计算
function outerFunction(a, b) {
 return innerFunction(a + b);
}

// 有优化：初始返回值不涉及栈帧
function outerFunction(a, b) {
 if (a < b) {
 return a;
 }
 return innerFunction(a + b);
}
// 有优化：两个内部函数都在尾部
function outerFunction(condition) {
 return condition ? innerFunctionA() : innerFunctionB();
}

```

差异化尾调用和递归尾调用是容易让人混淆的地方。无论是递归尾调用还是非递归尾调用，都可以
应用优化。引擎并不区分尾调用中调用的是函数自身还是其他函数。不过，这个优化在递归场景下的效
果是最明显的，因为递归代码最容易在栈内存中迅速产生大量栈帧。

## 第11章 异步函数

同步：每条指令都会严格按照它们出现的顺序来执行

异步：加入队列，稍后执行

### 1. 过去的异步操作

```js
function double(value, success, failure) {
  setTimeout(() => {
    try {
      if (typeof value !== 'number') {
        throw 'Must provide number as first argument';
      }
      success(2 * value);
    } catch (e) {
      failure(e);
    }
  }, 1000);
}

const successCallback = (x) => {
  double(x, (y) => console.log(`Success: ${y}`));
};
const failureCallback = (e) => console.log(`Failure: ${e}`);

// success需要double的返回值，successCallback需要success的返回值，回调地狱形成
double(3, successCallback, failureCallback);
// Success: 12（大约 1000 毫秒之后）

```

缺点一：必须在初始化异步操作时定义回调。异步函数的返回值只在短时间内存在，只有预备好将这个短时间内存在的值作为参数的回调才能接收到它。

缺点二：可能会出现回调地狱。

原因：异步操作不会立刻返回值，所以不能用一个变量来保存它的返回值，使用回调函数，表示一段时间之后要进行的操作

### 2. Promise

#### 2.1 基础概念

创建Promise，需要一个执行器函数作为参数，

```js
let p = new Promise(() => {});
setTimeout(console.log, 0, p); // Promise <pending>
// 之所以说是应付解释器，是因为如果不提供执行器函数，就会抛出 SyntaxError。
```

有三种状态，一旦改变就不可回退。

```
 待定（pending）
 兑现（fulfilled，有时候也称为“解决”，resolved）
 拒绝（rejected）
```

Promise有两种用途：

* 得到异步操作的状态，待定，成功，或者失败
* 可以得到成功的值，或者失败的理由

#### 2.2 Promise的初始化

```js
let p = new Promise(() => {});
setTimeout(console.log, 0, p); // Promise <pending>

let p1 = new Promise((resolve, reject) => resolve());
setTimeout(console.log, 0, p1); // Promise <resolved>

let p2 = new Promise((resolve, reject) => reject());
setTimeout(console.log, 0, p2); // Promise <rejected>
// Uncaught error (in promise) 
```

**执行器函数是同步执行的**

```js
new Promise(() => setTimeout(console.log, 0, 'executor'));
setTimeout(console.log, 0, 'promise initialized');
// executor
// promise initialized
```

##### 2.2.1 Promise.resolve()

实例化一个解决的promise，值为undefined

```js
let p1 = new Promise((resolve, reject) => resolve());
let p2 = Promise.resolve(); 
```

**1. 传入的第一个参数是普通值，这个值作为成功的值，多余参数被忽略**

```js
setTimeout(console.log, 0, Promise.resolve());
// Promise <resolved>: undefined
setTimeout(console.log, 0, Promise.resolve(3));
// Promise <resolved>: 3
// 多余的参数会忽略
setTimeout(console.log, 0, Promise.resolve(4, 5, 6));
// Promise <resolved>: 4 
```

**2. 如果传入的是一个promise，等于空包装，并且不会改变传入promise的状态**

包装前后相等

```js
let p = Promise.resolve(7);
setTimeout(console.log, 0, p === Promise.resolve(p));
// true
setTimeout(console.log, 0, p === Promise.resolve(Promise.resolve(p)));
// true
```

包装前后状态不变

```js
let p = new Promise(() => {});
setTimeout(console.log, 0, p); // Promise <pending>
setTimeout(console.log, 0, Promise.resolve(p)); // Promise <pending>
setTimeout(console.log, 0, p === Promise.resolve(p)); // true
```

**3. 传入的是错误对象，包装成解决的promise，值为错误对象**

```js
let p = Promise.resolve(new Error('foo'));
setTimeout(console.log, 0, p);
// Promise <resolved>: Error: foo
```

##### 2.2.2 Promise.reject()

初始化一个拒绝的promise，会抛出异步错误，无法通过try/catch解决（因为try/catch是同步的）只能通过拒绝事件处理程序解决。

```js
let p1 = new Promise((resolve, reject) => reject());
let p2 = Promise.reject();
```

```js
try {
 throw new Error('foo');
} catch(e) {
 console.log(e); // Error: foo
}
try {
 Promise.reject(new Error('bar'));
} catch(e) {
 console.log(e);
}
// Uncaught (in promise) Error: bar
```

**1. 传入的是普通值，这个值将作为拒绝的理由，传给后续拒绝处理程序**

```js
let p = Promise.reject(3);
setTimeout(console.log, 0, p); // Promise <rejected>: 3

p.then(null, (e) => setTimeout(console.log, 0, e)); // 3
```

**2. 传入的是promise，这个promise会成为拒绝的理由，和Promise.resolve()不同**

```js
setTimeout(console.log, 0, Promise.reject(Promise.resolve()));
// Promise <rejected>: Promise <resolved>
```

#### 2.3 Promise的原型方法

##### 2.3.1 then()

Promise.prototype.then()

then()函数可以接收两个参数(都必须是函数，不是函数会被忽略)，第一个作为onResolve处理程序，处理成功的值；第二个作为onReject处理程序，处理失败的理由。

```js
function onResolved(id) {
 setTimeout(console.log, 0, id, 'resolved');
}
function onRejected(id) {
 setTimeout(console.log, 0, id, 'rejected');
}

let p1 = new Promise((resolve, reject) => setTimeout(resolve, 3000));
let p2 = new Promise((resolve, reject) => setTimeout(reject, 3000));

p1.then(() => onResolved('p1'),
 () => onRejected('p1'));
p2.then(() => onResolved('p2'),
 () => onRejected('p2'));
//（3 秒后）
// p1 resolved
// p2 rejected

// 非函数处理程序会被静默忽略，不推荐
p1.then('gobbeltygook');
// 不传 onResolved 处理程序的规范写法
p2.then(null, () => onRejected('p2'));
// p2 rejected（3 秒后）
```

**重点来了，then()方法会返回一个新的Promise实例，这意味着可以接收一个异步操作的返回值**

```js
let p1 = new Promise(() => {});
let p2 = p1.then();

setTimeout(console.log, 0, p1); // Promise <pending>
setTimeout(console.log, 0, p2); // Promise <pending>
setTimeout(console.log, 0, p1 === p2); // false
```

这个新期约实例基于 onResovled 处理程序的返回值构建。换句话说，该处理程序的返回值会通过 Promise.resolve()包装来生成新期约。如果没有提供这个处理程序，则 Promise.resolve()就会 包装上一个期约解决之后的值。如果没有显式的返回语句，则 Promise.resolve()会包装默认的返回 值 undefined。

**1. 调用then()，不传处理程序，返回值和上一个promise一样**

```js
let p1 = Promise.resolve('foo');
// 若调用 then()时不传处理程序，则原样向后传
let p2 = p1.then();
setTimeout(console.log, 0, p2); // Promise <resolved>: foo
```

**2. 处理程序无返回值，用Promise.resolve()包装，值为undefined**

```js
// 这些都一样
let p3 = p1.then(() => undefined);
let p4 = p1.then(() => {});
let p5 = p1.then(() => Promise.resolve());

setTimeout(console.log, 0, p3); // Promise <resolved>: undefined
setTimeout(console.log, 0, p4); // Promise <resolved>: undefined
setTimeout(console.log, 0, p5); // Promise <resolved>: undefined
```

**3. 处理程序有返回值（普通值，错误对象，Promise实例），用Promise.resolve()包装该值**

```js
// 这些都一样
let p6 = p1.then(() => 'bar');
let p7 = p1.then(() => Promise.resolve('bar'));

setTimeout(console.log, 0, p6); // Promise <resolved>: bar
setTimeout(console.log, 0, p7); // Promise <resolved>: bar

// Promise.resolve()保留返回的期约
let p8 = p1.then(() => new Promise(() => {}));
let p9 = p1.then(() => Promise.reject());

// Uncaught (in promise): undefined
setTimeout(console.log, 0, p8); // Promise <pending>
setTimeout(console.log, 0, p9); // Promise <rejected>: undefined
```

**4. 抛出异常，返回拒绝的promise**

```js
let p10 = p1.then(() => { throw 'baz'; });
// Uncaught (in promise) baz
setTimeout(console.log, 0, p10); // Promise <rejected> baz
```

**5. 拒绝处理程序的返回值也适用于上面4条**

##### 2.3.2 catch()

等同于then(null, onRejected)，返回值也相同

##### 2.3.3 finally()

Promise.prototype.finally()方法用于给期约添加 onFinally 处理程序，这个处理程序在期 约转换为解决或拒绝状态时都会执行。这个方法可以避免 onResolved 和 onRejected 处理程序中出 现冗余代码。但 onFinally 处理程序没有办法知道期约的状态是解决还是拒绝，所以这个方法主要用 于添加清理代码。

**解决，拒绝的promise都会执行**

```js
let p1 = Promise.resolve();
let p2 = Promise.reject();
let onFinally = function() {
 setTimeout(console.log, 0, 'Finally!')
}
p1.finally(onFinally); // Finally
p2.finally(onFinally); // Finally
```

**会返回一个新promise**

```js
let p1 = new Promise(() => {});
let p2 = p1.finally();
setTimeout(console.log, 0, p1); // Promise <pending>
setTimeout(console.log, 0, p2); // Promise <pending>
setTimeout(console.log, 0, p1 === p2); // false 
```

**1. onFinally处理程序返回待定promise，结果返回待定promise**

```js
let p1 = Promise.resolve('foo');

let p9 = p1.finally(() => new Promise(() => {}));
setTimeout(console.log, 0, p9); // Promise <pending>
```

**2. onFinally处理程序返回拒绝的promise或抛出错误，结果返回拒绝的promise**

```js
let p10 = p1.finally(() => Promise.reject());
// Uncaught (in promise): undefined
setTimeout(console.log, 0, p10); // Promise <rejected>: undefined

let p11 = p1.finally(() => { throw 'baz'; });
// Uncaught (in promise) baz
setTimeout(console.log, 0, p11); // Promise <rejected>: baz
```

**3. 其他情况都会返回上一个promise，无论onFinally处理程序返回了什么**

处理程序结果还没出，返回待定的promise，出了结果按照上面三条规律来。

```js
let p1 = Promise.resolve('foo');
// 忽略解决的值
let p2 = p1.finally(
 () => new Promise((resolve, reject) => setTimeout(() => resolve('bar'), 100)));

setTimeout(console.log, 0, p2); // Promise <pending>
setTimeout(() => setTimeout(console.log, 0, p2), 200);
// 200 毫秒后：
// Promise <resolved>: foo
```

```js
let p1 = Promise.resolve('foo');
// 这里都会原样后传
let p2 = p1.finally();
let p3 = p1.finally(() => undefined);
let p4 = p1.finally(() => {});
let p5 = p1.finally(() => Promise.resolve());
let p6 = p1.finally(() => 'bar');
let p7 = p1.finally(() => Promise.resolve('bar'));
let p8 = p1.finally(() => Error('qux'));
setTimeout(console.log, 0, p2); // Promise <resolved>: foo
setTimeout(console.log, 0, p3); // Promise <resolved>: foo
setTimeout(console.log, 0, p4); // Promise <resolved>: foo
setTimeout(console.log, 0, p5); // Promise <resolved>: foo
setTimeout(console.log, 0, p6); // Promise <resolved>: foo
setTimeout(console.log, 0, p7); // Promise <resolved>: foo
setTimeout(console.log, 0, p8); // Promise <resolved>: foo
```

#### 2.4 非重入特性

onResolve，onReject, catch, onFinally中的代码都是异步执行的，先加入队列，之后再执行

```js
let p1 = new Promise((resolve, reject) => {
  console.log(1);
  resolve(2);
});

p1.then((value) => console.log(value));

console.log(3); // 1 3 2
```

#### 2.5 值的传递

到了落定状态后，期约会提供其解决值（如果兑现）或其拒绝理由（如果拒绝）给相关状态的处理 程序。拿到返回值后，就可以进一步对这个值进行操作。比如，第一次网络请求返回的 JSON 是发送第 二次请求必需的数据，那么第一次请求返回的值就应该传给 onResolved 处理程序继续处理。当然，失 败的网络请求也应该把 HTTP 状态码传给 onRejected 处理程序。

成功的值会作为onResolve的参数

失败的值会作为onReject的参数

```js
let p1 = new Promise((resolve, reject) => resolve('foo'));
p1.then((value) => console.log(value)); // foo

let p2 = new Promise((resolve, reject) => reject('bar'));
p2.catch((reason) => console.log(reason)); // bar
```

#### 2.6 错误处理

错误处理是异步操作，不会终止后面代码的运行，只能用catch或者then(null，onReject)处理

```js
new Promise((resolve, reject) => {
 console.log('begin asynchronous execution');
 reject(Error('bar'));
}).catch((e) => {
 console.log('caught error', e);
}).then(() => {
 console.log('continue asynchronous execution');
});
// begin asynchronous execution
// caught error Error: bar
// continue asynchronous execution
```

#### 2.7 promise连锁

串行化异步任务，每一个promise都需要等待之前的promise包装的异步任务完成，成功解决回调地狱的问题

```js
let p1 = new Promise((resolve, reject) => {
 console.log('p1 executor');
 setTimeout(resolve, 1000);
});
p1.then(() => new Promise((resolve, reject) => {
 console.log('p2 executor');
 setTimeout(resolve, 1000);
 }))
 .then(() => new Promise((resolve, reject) => {
 console.log('p3 executor');
 setTimeout(resolve, 1000);
 }))
 .then(() => new Promise((resolve, reject) => {
 console.log('p4 executor');
 setTimeout(resolve, 1000);
 }));
```

回调函数的方式：

```js
function delayedExecute(str, callback = null) {
 setTimeout(() => {
 console.log(str);
 callback && callback();
 }, 1000)
}

delayedExecute('p1 callback', () => {
	delayedExecute('p2 callback', () => {
 		delayedExecute('p3 callback', () => {
 			delayedExecute('p4 callback');
 			});
 		});
	});
// p1 callback（1 秒后）
// p2 callback（2 秒后）
// p3 callback（3 秒后）
// p4 callback（4 秒后）

```

#### 2.8 promise图

因为一个期约可以有任意多个处理程序，所以期约连锁可以构建**有向非循环图**的结构。这样，每个 期约都是图中的一个节点，而使用实例方法添加的处理程序则是有向顶点。因为图中的每个节点都会等 待前一个节点落定，所以图的方向就是期约的解决或拒绝顺序。

![image-20201129145835048](C:\Users\洪明辉\AppData\Roaming\Typora\typora-user-images\image-20201129145835048.png)

期约图的一种，实现了二叉树的层次遍历

```js
let A = new Promise((resolve, reject) => {
 console.log('A');
 resolve();
});
let B = A.then(() => console.log('B'));
let C = A.then(() => console.log('C'));
B.then(() => console.log('D'));
B.then(() => console.log('E'));
C.then(() => console.log('F'));
C.then(() => console.log('G'));
// A
// B
// C
// D
// E
// F
// G 
```

树只是期约图的一种形式。考虑到根节点不一定唯一，且多个期约也可以组合成一个期约（通过下 一节介绍的 Promise.all()和 Promise.race()），所以有向非循环图是体现期约连锁可能性的最准确表达。

#### 2.9 all() race()

##### 2.9.1 Promise.all()

Promise.all()静态方法创建的期约会在一组期约全部解决之后再解决。这个静态方法接收一个可迭代对象，可迭代对象中的元素会用Promise.resolve()包装，返回一个新期约：

存在拒绝，就会返回拒绝的promise，

不存在拒绝，存在待定，就会返回待定的promise,

其他情况，返回解决的promise

```js
// 永远待定
let p1 = Promise.all([new Promise(() => {})]);
setTimeout(console.log, 0, p1); // Promise <pending>

// 一次拒绝会导致最终期约拒绝
let p2 = Promise.all([
 Promise.resolve(),
 Promise.reject(),
 Promise.resolve()
]);
setTimeout(console.log, 0, p2); // Promise <rejected>
// Uncaught (in promise) undefined 
```

**如果所有期约都成功解决，则合成期约的解决值就是所有包含期约解决值的数组，按照迭代器顺序**：

```js
let p = Promise.all([
 Promise.resolve(3),
 Promise.resolve(),
 Promise.resolve(4)
]);

p.then((values) => setTimeout(console.log, 0, values)); // [3, undefined, 4]
```

**如果有期约拒绝，则第一个拒绝的期约会将自己的理由作为合成期约的拒绝理由**。之后再拒绝的期
约不会影响最终期约的拒绝理由。不过，这并不影响所有包含期约正常的拒绝操作。合成的期约会静默
处理所有包含期约的拒绝操作，如下所示：

```js
// 虽然只有第一个期约的拒绝理由会进入
// 拒绝处理程序，第二个期约的拒绝也
// 会被静默处理，不会有错误跑掉
let p = Promise.all([
 Promise.reject(3),
 new Promise((resolve, reject) => setTimeout(reject, 1000))
]);
p.catch((reason) => setTimeout(console.log, 0, reason)); // 3
// 没有未处理的错误

```

##### 2.9.2 Promise.race()

Promise.race()静态方法返回一个包装期约，是一组集合中最先解决或拒绝的期约的镜像。这个 方法接收一个可迭代对象，返回一个新期约：

```js
// 解决先发生，超时后的拒绝被忽略
let p1 = Promise.race([
 Promise.resolve(3),
 new Promise((resolve, reject) => setTimeout(reject, 1000))
]);
setTimeout(console.log, 0, p1); // Promise <resolved>: 3
// 拒绝先发生，超时后的解决被忽略
let p2 = Promise.race([
 Promise.reject(4),
 new Promise((resolve, reject) => setTimeout(resolve, 1000))
]);
setTimeout(console.log, 0, p2); // Promise <rejected>: 4
// 迭代顺序决定了落定顺序
let p3 = Promise.race([
 Promise.resolve(5),
 Promise.resolve(6),
 Promise.resolve(7)
]);
setTimeout(console.log, 0, p3); // Promise <resolved>: 5
```

如果有一个期约拒绝，只要它是第一个落定的，就会成为拒绝合成期约的理由。之后再拒绝的期约
不会影响最终期约的拒绝理由。不过，这并不影响所有包含期约正常的拒绝操作。与 Promise.all()
类似，合成的期约会静默处理所有包含期约的拒绝操作，如下所示：

```js
// 虽然只有第一个期约的拒绝理由会进入
// 拒绝处理程序，第二个期约的拒绝也
// 会被静默处理，不会有错误跑掉
let p = Promise.race([
 Promise.reject(3),
 new Promise((resolve, reject) => setTimeout(reject, 1000))
]);
p.catch((reason) => setTimeout(console.log, 0, reason)); // 3
// 没有未处理的错误
```

### 3. async await

Promise的问题是，想用到异步操作的返回值，就必须使用then()。

#### 3.1 async

async 关键字用于声明异步函数。这个关键字可以用在函数声明、函数表达式、箭头函数和方法上：

```js
async function foo() {}

let bar = async function() {};

let baz = async () => {};

class Qux {
 async qux() {}
} 
```

声明之后，函数仍然是同步执行的，返回值会用Promise.resolve()包装，没有返回值，包装默认的undefined

**拒绝的promise，不会被catch()捕获**

```js
async function foo() {
 console.log(1);
 Promise.reject(3);
}
// Attach a rejected handler to the returned promise
foo().catch(console.log);
console.log(2);
// 1
// 2
// Uncaught (in promise): 3
```

#### 3.2 await

await 关键字会**暂停执行异步函数后面的代码**，让出 JavaScript 运行时的执行线程。这个行 为与生成器函数中的 yield 关键字是一样的。await 关键字同样是尝试“解包”对象的值，然后将这 个值传给表达式，再异步恢复异步函数的执行。

**1. await后面接普通值，返回的就是这个值本身**

```js
// 等待一个原始值
async function foo() {
 console.log(await 'foo');
}
foo();
// foo
```

**2. await后面接解决的Promise，返回的是成功值**

即Promise.resolve()的参数

```js
// 等待一个期约
async function qux() {
 console.log(await Promise.resolve('qux')); // redutant statement
 
}
qux();
// qux
```

**3. 抛出错误，返回拒绝的promise**

```js
async function foo() {
 console.log(1);
 await (() => { throw 3; })();
}
// 给返回的期约添加一个拒绝处理程序
foo().catch(console.log);
console.log(2);
// 1
// 2
// 3
```

**4. await后面接拒绝的promise，抛出异步错误，返回拒绝的promise**

```js
async function foo() {
 console.log(1);
 await Promise.reject(3);
 console.log(4); // 这行代码不会执行
}
// 给返回的期约添加一个拒绝处理程序
foo().catch(console.log);
console.log(2);
// 1
// 2
// 3
```

await后面跟着值，会异步求值，后面是语句，该同步同步，该异步异步。（我猜的）

```js
async function test() {
      // await console.log(1); // 1 2 3，这里为什么先输出1了
      console.log(await 1); // 2 1 3
      console.log(3);
    }

    test();
    console.log(2);
```

#### 3.3 实现sleep()

```js
function sleep(delay) {
  return new Promise(resolve => {
    setTimeout(resolve, delay);
  })
}

async function foo() {
  await sleep(1500);
}

let start = Date.now();

foo().then(() => console.log(Date.now() - start)); // 1502

```



